/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author dianacastro
 */
public class FAutenticación extends javax.swing.JFrame {

    /**
     * Creates new form FAutenticación
     */
    public FAutenticación() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Autentificación");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDestinatario = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblContrasenia = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        lblRemitente1 = new javax.swing.JLabel();
        pfContrasenia = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        lblDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblDestinatario.setText("Para ");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContrasenia.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblContrasenia.setText("Contraseña");
        getContentPane().add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtDestinatario.setBackground(new java.awt.Color(255, 255, 255));
        txtDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        getContentPane().add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 210, -1));

        lblRemitente1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblRemitente1.setText("Correo");
        getContentPane().add(lblRemitente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        pfContrasenia.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        getContentPane().add(pfContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 210, 30));

        btnAceptar.setBackground(new java.awt.Color(0, 153, 255));
        btnAceptar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("");
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 100, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-la-izquierda (1).png"))); // NOI18N
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 40));

        lblFondo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blanco.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAutenticación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblRemitente1;
    private javax.swing.JPasswordField pfContrasenia;
    private javax.swing.JTextField txtDestinatario;
    // End of variables declaration//GEN-END:variables
}
