/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Validaciones.Validaciones;
import java.awt.Frame;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dianacastro
 */
public class FAutenticación extends javax.swing.JFrame {
    Validaciones validaciones;
    /**
     * Creates new form FAutenticación
     */
    public FAutenticación() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Autentificación");
        validaciones = new Validaciones();
        llenarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDestinatario = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblContrasenia = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        lblRemitente1 = new javax.swing.JLabel();
        pfContrasenia = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cbServidor = new javax.swing.JComboBox<>();
        lblServidor = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        lblDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblDestinatario.setText("Para ");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContrasenia.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblContrasenia.setText("Contraseña");
        getContentPane().add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinatarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 250, -1));

        lblRemitente1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblRemitente1.setText("Correo");
        getContentPane().add(lblRemitente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        pfContrasenia.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        pfContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(pfContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, 30));

        btnAceptar.setBackground(new java.awt.Color(0, 153, 255));
        btnAceptar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 120, 40));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-la-izquierda (1).png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 40));

        getContentPane().add(cbServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 250, -1));

        lblServidor.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblServidor.setText("Servidor");
        getContentPane().add(lblServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 20));

        lblFondo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blanco.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
         if (validarCampos()) {
            FMailSender mailSender = new FMailSender(txtDestinatario.getText(), pfContrasenia.getText(), cbServidor.getSelectedItem().toString());
            mailSender.show();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void pfContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfContraseniaActionPerformed

    private void txtDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinatarioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed
    private boolean validarCampos() {
        if (!validaciones.esVacio(txtDestinatario.getText(), pfContrasenia.getText())) {
            JOptionPane.showMessageDialog(this, "Debes llenar todos los campos.", "Error de llenado", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!validaciones.validarFormatoCorreo(txtDestinatario.getText())) {
            JOptionPane.showMessageDialog(this, "Ingresa un correo electronico valido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
            return false;
        }
        
        if (!validaciones.validarCorreo(txtDestinatario.getText(), cbServidor.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "El dominio del correo electronico debe coincidir con el servicio elegido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void limpiarCampos(){
        txtDestinatario.setText("");
        pfContrasenia.setText("");
    }
    
    private void llenarComboBox(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Gmail");
        modelo.addElement("Outlook");
        modelo.addElement("Hotmail");
        modelo.addElement("Yahoo");
        cbServidor.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAutenticación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAutenticación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbServidor;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblRemitente1;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JPasswordField pfContrasenia;
    private javax.swing.JTextField txtDestinatario;
    // End of variables declaration//GEN-END:variables
}
