/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;


import Fachada.FacadeMailSender;
import Validaciones.Validaciones;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dianacastro
 */
public final class FMailSender extends javax.swing.JFrame {
    String password;
    String correoRemitente;
    String server;
    Validaciones validaciones;
   
    
    public FMailSender(String correoRemitente, String password, String server) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mail Sender");
        
        this.password = password;
        this.correoRemitente = correoRemitente;
        this.server = server;
        this.validaciones = new Validaciones();
        inicializarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDestinatario = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        lblAsunto = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAMensaje = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbServidor = new javax.swing.JComboBox<>();
        lblServidor = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(501, 431));
        setMinimumSize(new java.awt.Dimension(501, 431));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblDestinatario.setText("Para ");
        getContentPane().add(lblDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        getContentPane().add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 340, -1));

        lblAsunto.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblAsunto.setText("Asunto");
        getContentPane().add(lblAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        getContentPane().add(txtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 340, 30));

        txtAMensaje.setColumns(20);
        txtAMensaje.setRows(5);
        jScrollPane1.setViewportView(txtAMensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 420, 180));

        btnEnviar.setBackground(new java.awt.Color(0, 153, 255));
        btnEnviar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setToolTipText("");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 80, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        getContentPane().add(cbServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 340, -1));

        lblServidor.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblServidor.setText("Servidor");
        getContentPane().add(lblServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 20));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-la-izquierda (1).png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blanco.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 514, 441));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        new FacadeMailSender().enviarMessage(
                correoRemitente, txtDestinatario.getText(), txtAsunto.getText(), txtAMensaje.getText(), password, 
                server);
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
             limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FAutenticación FaAurenticacion = new FAutenticación();
        FaAurenticacion.show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void inicializarComboBox(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement(server);
        cbServidor.setModel(modelo);
        cbServidor.setEnabled(false);
    }
    
    public void limpiarCampos(){
        txtDestinatario.setText("");
        txtAsunto.setText("");
        txtAMensaje.setText("");
    }

     public boolean validarCampos(){
         if (!validaciones.esVacioForm(txtDestinatario.getText(), txtAsunto.getText(), txtAMensaje.getText())) {
            JOptionPane.showMessageDialog(this, "Debes llenar todos los campos.", "Error de llenado", JOptionPane.ERROR_MESSAGE);
            return false;
        }
         return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JTextArea txtAMensaje;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtDestinatario;
    // End of variables declaration//GEN-END:variables
}
