/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author dianacastro
 */
public class FMailSender extends javax.swing.JFrame {

    /**
     * Creates new form MailSender
     */
    public FMailSender() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mail Sender");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServidor = new javax.swing.JLabel();
        cbServidor = new javax.swing.JComboBox<>();
        lblDestinatario = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        lblAsunto = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAMensaje = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(501, 431));
        setMinimumSize(new java.awt.Dimension(501, 431));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServidor.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblServidor.setText("Servidor");
        getContentPane().add(lblServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 20));

        cbServidor.setBackground(new java.awt.Color(255, 255, 255));
        cbServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServidorActionPerformed(evt);
            }
        });
        getContentPane().add(cbServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 320, -1));

        lblDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblDestinatario.setText("Para ");
        getContentPane().add(lblDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txtDestinatario.setBackground(new java.awt.Color(255, 255, 255));
        txtDestinatario.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        getContentPane().add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 340, -1));

        lblAsunto.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblAsunto.setText("Asunto");
        getContentPane().add(lblAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtAsunto.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 340, 30));

        txtAMensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtAMensaje.setColumns(20);
        txtAMensaje.setRows(5);
        jScrollPane1.setViewportView(txtAMensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 420, 180));

        btnEnviar.setBackground(new java.awt.Color(0, 153, 255));
        btnEnviar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setToolTipText("");
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 80, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blanco.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 514, 441));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMailSender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cbServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JTextArea txtAMensaje;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtDestinatario;
    // End of variables declaration//GEN-END:variables
}
